export const countries = {
  Algeria: "الجزائر",
  Bahrain: "البحرين",
  Comoros: "جزر القمر",
  Djibouti: "جيبوتي",
  Egypt: "مصر",
  Iraq: "العراق",
  Jordan: "الأردن",
  Kuwait: "الكويت",
  Lebanon: "لبنان",
  Libya: "ليبيا",
  Mauritania: "موريتانيا",
  Morocco: "المغرب",
  Oman: "عمان",
  Palestine: "فلسطين",
  Qatar: "قطر",
  SaudiArabia: "السعودية",
  Somalia: "الصومال",
  Sudan: "السودان",
  Syria: "سوريا",
  Tunisia: "تونس",
  UnitedArabEmirates: "الإمارات",
  Yemen: "اليمن",
};
